FROM node:16-buster

WORKDIR /opt/app

COPY ./db/migrations ./db/migrations 

COPY ./knexfile.js ./knexfile.js

COPY ./wait-for-it.sh ./wait-for-it.sh

RUN chmod +x wait-for-it.sh

RUN npm init -y 

RUN npm install knex pg dotenv
