version: "3.9"

networks:
  integration-tests:
    driver: bridge

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hangman_db
    networks:
      - integration-tests

  build-db-relationships:
    container_name: build-db-relationships 
    build:
      context: .
      dockerfile: Dockerfile.migrations 
    environment:
      DATABASE_PORT: 5432
      DATABASE_HOST: postgres
      DATABASE_NAME: hangman_db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_POOL_MIN: 2
      DATABASE_POOL_MAX: 10
    depends_on:
      - postgres 
    command:
      [
        "./wait-for-it.sh",
        "postgres:5432",
        "--strict",
        "--timeout=300",
        "--",
        "./node_modules/knex/bin/cli.js",
        "migrate:latest",
      ]
    networks:
      - integration-tests

  test-integration:
    container_name: test-integration 
    build: 
      context: .
      dockerfile: Dockerfile.test-integration
    environment:
      DATABASE_PORT: 5432
      DATABASE_HOST: postgres
      DATABASE_NAME: hangman_db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_POOL_MIN: 2
      DATABASE_POOL_MAX: 10
    depends_on:
      - postgres 
      - build-db-relationships
    networks:
      - integration-tests
