name: Docker Image hangman API CD

on:
  workflow_dispatch:

jobs:
  build:
    uses: .github/workflows/reusable-node-build.yml
    with:
      node-version: 16
      working-directory: hangman-api
    # runs-on: ubuntu-latest

    # steps:
      # - uses: actions/checkout@v3
      # - uses: actions/setup-node@v3
      #   with: 
      #     node-version: 16
      #     cache: 'npm'
      #     cache-dependency-path: hangman-api/package-lock.json
      # - name: build
      #   working-directory: ./hangman-api
      #   run: |
      #     npm ci 
      #     npm run build --if-present
      # - uses: actions/upload-artifact@v3 
      #   with:
      #     name: build-code
      #     path: hangman-api/dist/


  delivery:
    
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: build-code
        path: hangman-api/dist/
    - name: Build and Push Docker Image
      working-directory: ./hangman-api
      env:
        DOCKER_USER: "jaimesalas"
        DOCKER_REPOSITORY: "hangman-api"
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: | 
        echo $DOCKER_PASSWORD | docker login --username $DOCKER_USER --password-stdin
        image=$DOCKER_USER/$DOCKER_REPOSITORY:$(date +%s)
        docker build . --file Dockerfile.workflow --tag $image
        docker push $image
    