name: Reusable Node Build 

on: 
  workflow_call:
    inputs:
      node-version: 
        required: true
        type: number
      working-directory:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
          cache-dependency-path: ${{ inputs.working-directory }}/package-lock.json
      - name: build 
        working-directory: ${{ inputs.working-directory }}
        run: |
          npm ci 
          npm run build --if-present
      - uses: actions/upload-artifact@v3 
        with:
          name: build-code
          path: ${{ inputs.working-directory }}/dist/
